//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabNeuropsico.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LabNeuropsico.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP TABLE IF EXISTS public.avaliacao;
        ///
        ///CREATE TABLE public.avaliacao (
        ///	id_avaliacao BIGSERIAL PRIMARY KEY,
        ///	id_instrumento BIGINT NOT NULL REFERENCES instrumento(id_instrumento),
        ///	id_relatorio BIGINT NOT NULL REFERENCES relatorio(id_relatorio),
        ///	excluido BOOL NOT NULL DEFAULT false
        ///);.
        /// </summary>
        internal static string avaliacao_create {
            get {
                return ResourceManager.GetString("avaliacao_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP TABLE IF EXISTS public.campo;
        ///
        ///CREATE TABLE public.campo (
        ///	id_campo BIGSERIAL PRIMARY KEY,
        ///	id_instrumento BIGINT NOT NULL REFERENCES instrumento(id_instrumento),
        ///	nome TEXT NOT NULL,
        ///	tipo TEXT NOT NULL,
        ///	excluido BOOL NOT NULL DEFAULT false
        ///);.
        /// </summary>
        internal static string campo_create {
            get {
                return ResourceManager.GetString("campo_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP TABLE IF EXISTS public.instrumento;
        ///
        ///CREATE TABLE public.instrumento (
        ///	id_instrumento BIGSERIAL PRIMARY KEY,
        ///	nome TEXT NOT NULL,
        ///	tipo TEXT NOT NULL,
        ///	excluido BOOL NOT NULL DEFAULT false
        ///);.
        /// </summary>
        internal static string instrumento_create {
            get {
                return ResourceManager.GetString("instrumento_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap loading {
            get {
                object obj = ResourceManager.GetObject("loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP TABLE IF EXISTS public.paciente;
        ///
        ///CREATE TABLE public.paciente (
        ///    id_paciente BIGSERIAL PRIMARY KEY,
        ///    nome TEXT NOT NULL,
        ///    data_nasc DATE NOT NULL,
        ///    lateralidade CHAR,
        ///    escolaridade TEXT,
        ///    sexo CHAR NOT NULL,
        ///    nacionalidade CHAR NOT NULL,
        ///    responsavel TEXT,
        ///    ocup_responsavel TEXT,
        ///    prontuario TEXT,
        ///    hospital CHAR NOT NULL,
        ///    condicao TEXT,
        ///    excluido BOOLEAN NOT NULL DEFAULT FALSE
        ///);.
        /// </summary>
        internal static string paciente_create {
            get {
                return ResourceManager.GetString("paciente_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP TABLE IF EXISTS public.relatorio;
        ///
        ///CREATE TABLE public.relatorio (
        ///	id_relatorio BIGSERIAL PRIMARY KEY,
        ///    id_paciente BIGINT NOT NULL REFERENCES paciente(id_paciente),
        ///	num_relatorio TEXT,
        ///	queixa_clinica TEXT NOT NULL,
        ///	inicio_aval DATE NOT NULL,
        ///	fim_aval DATE NOT NULL,
        ///	excluido BOOLEAN NOT NULL DEFAULT false
        ///);.
        /// </summary>
        internal static string relatorio_create {
            get {
                return ResourceManager.GetString("relatorio_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search {
            get {
                object obj = ResourceManager.GetObject("search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP TABLE IF EXISTS public.usuario;
        ///
        ///CREATE TABLE public.usuario (
        ///    id_usuario BIGSERIAL PRIMARY KEY,
        ///    nome TEXT NOT NULL,
        ///    login VARCHAR(16) UNIQUE NOT NULL,
        ///    senha TEXT NOT NULL,
        ///    email VARCHAR(254) UNIQUE NOT NULL,
        ///    hospital CHAR DEFAULT &apos;a&apos;,
        ///    obs TEXT,
        ///	admin BOOLEAN NOT NULL DEFAULT false,
        ///    excluido BOOLEAN NOT NULL DEFAULT false
        ///);.
        /// </summary>
        internal static string usuario_create {
            get {
                return ResourceManager.GetString("usuario_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP TABLE IF EXISTS public.valid;
        ///
        ///CREATE TABLE public.valid (
        ///	valido BOOL NOT NULL DEFAULT true
        ///);.
        /// </summary>
        internal static string valid_create {
            get {
                return ResourceManager.GetString("valid_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP TABLE IF EXISTS public.valor;
        ///
        ///CREATE TABLE public.valor (
        ///	id_valor BIGSERIAL PRIMARY KEY,
        ///	id_avaliacao BIGINT NOT NULL REFERENCES avaliacao(id_avaliacao),
        ///	id_campo BIGINT NOT NULL REFERENCES campo(id_campo),
        ///	vdate DATE, 
        ///	vint INTEGER, 
        ///	vdouble NUMERIC(10,2),
        ///	vtext TEXT,
        ///	excluido BOOL NOT NULL DEFAULT false
        ///);.
        /// </summary>
        internal static string valor_create {
            get {
                return ResourceManager.GetString("valor_create", resourceCulture);
            }
        }
    }
}
